import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ul className="flex p-4 border bg-gray-50 rounded-lg">
          <li>
            <Link href="/" className="pr-4">Home</Link>
          </li>
          <li>
            <Link href="/post">Post</Link>
          </li>
        </ul>
        {children}
      </body>
    </html>
  );
}
